---
title: "fish_pass"
author: "Mike Allen"
date: "12/7/2021"
output: html_document
---

# Packages
Load packages, functions, & data; format data
```{r}
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyr)
library(wesanderson)
library(lubridate)
library(readxl)
source("scripts/fishsum_function.R")
`%notin%` <- Negate(`%in%`)

# read in tagging data
# note: currently excludes herring w/ "226000011055/35/85" tag

tags <- read_xlsx(
  "other/1 IFW Tagging Data Golden Master 2_25_22.xlsx",
  sheet = "All Tagged Fish") %>%
  rename(tag = 'Tag Number',
         datetime = as.character('Date and Time'),
         Common.Name = 'Common Name') %>%
  mutate(tag = as.numeric(tag)) %>%
  filter(is.na(tag) == FALSE) %>%
  mutate(tag_short = str_sub(tag, - 9, - 1),
         tag_time = ymd_hms(datetime, 
                           tz = "America/New_York"))

# video time series
v_temp <- 
  read_xlsx("other/2 IFW Video Data Golden Master 11_2_21.xlsx",
               sheet = "Grouped") %>%
  select(Date, species = Species) %>%
  mutate(year = year(Date)) %>%
  group_by(species, year) %>%
  tally() %>%
  filter(species %in% c("American Shad", "River Herring spp."))

# historic Island Farm Wier Video counts
shad_hist <- data.frame(species = "American Shad",
                        year = c(1996:2005),
                        n = c(48, 76, 149, 582, NA, 717, 
                                1114, 362, NA, 13))

herring_hist <- data.frame(species = "River Herring spp.",
                           year = c(1996:2005),
                        n = c(0, 117, 9, 114, NA, 61, 
                                17, 12, NA, 0))

# combine recent and historic video count data
v <- v_temp %>%
  bind_rows(shad_hist, herring_hist) %>%
  arrange(species, year)

# Compile receiver data
# Data are compiled, filtered, and cleaned within these scripts. Anthony should review to ensure all filtering was OK.
source("scripts/compile_pings_2012.R")
source("scripts/compile_pings_2013.R")
source("scripts/compile_pings_2014.R")
source("scripts/compile_pings_2015.R")
source("scripts/compile_pings_2016.R")
source("scripts/compile_pings_2017.R")
source("scripts/compile_pings_2018.R")
source("scripts/compile_pings_2019.R")

# Extracting & summarizing fish tag data
fish2012_sum <- fishsum(data2012)
fish2013_sum <- fishsum(data2013)
fish2014_sum <- fishsum(data2014)
fish2015_sum <- fishsum(data2015)
fish2016_sum <- fishsum(data2016)
fish2017_sum <- fishsum(data2017)
fish2018_sum <- fishsum(data2018)
fish2019_sum <- fishsum(data2019)
fish_sum <- fish2019_sum %>%
  bind_rows(fish2018_sum, fish2017_sum, fish2016_sum,
            fish2015_sum, fish2014_sum, fish2013_sum, 
            fish2012_sum) %>%
  arrange(year, Common.Name, tag_time)

# remove unneeded objects
rm(fish2019_sum, fish2018_sum, fish2017_sum, fish2016_sum,
            fish2015_sum, fish2014_sum, fish2013_sum, 
            fish2012_sum, v_temp)

# subset target species and create 1/0 passage variable (did the fish reach A4)
f <- tags %>%
  select(tag_short, Common.Name, tag_time) %>%
  filter(Common.Name %in% c("American Shad",
                            "River Herring",
                            "Blueback Herring",
                            "Alewife")) %>%
  left_join(select(fish_sum, year, tag_short, first_ping_A4), by = "tag_short") %>%
  filter(!duplicated(tag_short)) %>% # remove 3 duplicates (inter-year returns)
  mutate(passage = case_when(is.na(first_ping_A4) ~ 0,
                               TRUE ~ 1),
         year = as.factor(case_when(is.na(year) ~ year(tag_time),
                          TRUE ~ year)),
         year_num = as.numeric(as.factor(year)),
         year_char = paste0("y", year),
         sp = as.factor(case_when(grepl(Common.Name, pattern = "Herring|Alewife") ~
                          "Herring",
                        TRUE ~ "Shad")))

shad_df <- f %>%
  filter(sp == "Shad")

herring_df <- f %>%
  filter(sp == "Herring")

# examine shad data
shad_raw_sum <- cbind.data.frame(
  trials = aggregate(shad_df$passage, 
                     by = list(shad_df$year), length),
  successes = aggregate(shad_df$passage, 
                        by = list(shad_df$year), sum)[,2],
  prop = aggregate(shad_df$passage, by = list(shad_df$year), mean)[,2]
  ) %>%
  mutate(year = as.numeric(as.character(trials.Group.1)),
         species = "American Shad") %>%
  select(-trials.Group.1)

# examine herring data
herring_raw_sum <- cbind.data.frame(
  trials = aggregate(herring_df$passage, 
                     by = list(herring_df$year), length),
  successes = aggregate(herring_df$passage, 
                        by = list(herring_df$year), sum)[,2],
  prop = aggregate(herring_df$passage, by = list(herring_df$year), mean)[,2]
  ) %>%
  mutate(year = as.numeric(as.character(trials.Group.1)),
         species = "Herring spp.") %>%
  select(-trials.Group.1)

raw_sum <- rbind(shad_raw_sum, herring_raw_sum)

shad_data <- list(
  D = 1,
  N = nrow(filter(f, Common.Name == "American Shad")),
  L = length(unique(filter(f, Common.Name == "American Shad")$year)),
  y = filter(f, Common.Name == "American Shad")$passage,
  ll = as.numeric(as.factor(filter(f, Common.Name == "American Shad")$year)),
  x = rbind(rep(1, nrow(filter(f, Common.Name == "American Shad"))))
)

# Format fish data for "passage proportion" analysis

# combine raw data summaries
both <- rbind(shad_raw_sum, herring_raw_sum) %>%
  select(N = trials.x, z = successes, -prop, year) %>%
  mutate(year = as.numeric(as.factor(year)),
         fish = c(rep(1,7), rep(2,8)),
         fishyears = 1:15) #%>%
  #bind_rows(data.frame(N=0,z = 0,year = 7, fish = 1))

nfishyears <- 15
nyears <- 8
nfish <- 2

# bundle data for jags
fish_jags_data <- list(
  nfish = nfish,
  nfishyears = nfishyears,
  z = both$z,
  N = both$N,
  c = both$fish,
  fallback_detect = c(rep(1,33), rep(0,106)),
  fallback_n = 139
)
```
# Save data and diagnostic plot files for inspection
Need to be checked by Anthony.
```{r}
# source("scripts/save_diagnostics.R")
```
# JAGS model for fish passage proportion
Hyperparameters for both omega[c] and kappa[c]
```{r}

cat(file = "scripts/fish_mod.txt",
"
model{
for(s in 1:nfishyears){
  z[s] ~ dbin(theta[s], N[s])
  theta[s] ~ dbeta( omega[c[s]]*(kappa[c[s]]-2 )+1 ,
                    (1-omega[c[s]])*(kappa[c[s]]-2)+1)
}  

for( c in 1:nfish){
omega[c] ~ dbeta( omega0*(kappa0-2)+1,
                  (1-omega0)*(kappa0-2)+1 )
kappa[c] <- kappaMinusTwo[c] + 2
kappaMinusTwo[c] ~ dgamma(S0, R0) 

}

fallback_p ~ dunif(0,1) # dbeta(3,3)
for(i in 1:length(fallback_detect)){
fallback_detect[i] ~ dbern(fallback_p)
}

# corrected for imperfect detection in the arrays
fallback_p_cor <- fallback_p / 0.5

omega0 ~ dbeta(3, 3)
kappa0 <- kappaMinusTwo0 + 2
kappaMinusTwo0 ~ dgamma(0.1, 0.01) # mean=1, sd = 10

S0 ~ dgamma(0.1, 0.01)
R0 ~ dgamma(0.1, 0.01)
}
"
)

fish_mod_beta3_3g <- jagsUI::jags(data = fish_jags_data,
             model.file = "scripts/fish_mod.txt",
             n.iter = 500000, n.burnin = 400000,
             parameters.to.save = c("theta", "omega", "kappa",
                                    "S0", "R0", "fallback_p",
                                    "fallback_p_cor"),
             n.chains = 3, parallel = T, n.thin = 100,
             inits = function()list(omega =
                                      c(rnorm(1,.47,.01),
                                        rnorm(1,.9,.01)),
                                    kappaMinusTwo = c(rnorm(1,25,2),
                                                      rnorm(1,11,2))
             ))
fish_mod_beta3_3g
fish_mod <- fish_mod_beta3_3g
# saveRDS(fish_mod, "other/output/fish_jags_mod_hyperkappa_beta3_3g_030422_all_converged.rds")

# before Alewife, was using:
# other/output/fish_jags_mod_hyperkappa_beta3_3b_012822_all_converged.rds
# fish_mod <- readRDS("other/output/fish_jags_mod_hyperkappa_beta3_3f_030322_all_converged.rds")
fish_mod 
dev.new(); plot(fish_mod)
thetas <- tidybayes::gather_draws(fish_mod, theta[i]) %>%
  group_by(i) %>%
  summarise(theta_mean = mean(.value),
            theta_q2.5 = quantile(.value, .025),
            theta_q97.5 = quantile(.value, .975),
            theta_q10 = quantile(.value, .1),
            theta_q90 = quantile(.value, .9)) %>%
  mutate(year = c(2012:2017,2019,2012:2019),
         species = c(rep("American Shad", 7), rep("Herring spp.", 8))) %>%
  left_join(raw_sum) 

omegas <- tidybayes::gather_draws(fish_mod, omega[i]) %>%
  group_by(i) %>%
  summarise(omega_mean = mean(.value),
            omega_q2.5 = quantile(.value, .025),
            omega_q97.5 = quantile(.value, .975),
            omega_q10 = quantile(.value, .1),
            omega_q90 = quantile(.value, .9)) %>%
  mutate(species = c("American Shad", "Herring spp."))


thetas %>%
  ggplot() +
    geom_vline(data = omegas, aes(xintercept = omega_mean), size = 0.5,
             color = "red") +
      geom_vline(data = omegas, aes(xintercept = omega_q2.5), size = 0.5,
             color = "red", lty = 2) +
        geom_vline(data = omegas, aes(xintercept = omega_q97.5), size = 0.5,
             color = "red", lty = 2) +
  geom_errorbar(aes(xmin = theta_q2.5,
                    xmax = theta_q97.5,
                    y = year), width = 0) +
  geom_errorbar(aes(xmin = theta_q10,
                    xmax = theta_q90,
                    y = year), size = 1, width = 0) +
  geom_point(aes(x = theta_mean,
                 y = year), size = 4) +
  facet_wrap(~species) +
  scale_x_continuous(limits = c(0,1.1),
                     breaks = seq(0,1,0.2)) +
  scale_y_continuous(breaks = 2012:2019) +
  theme_bw() +
  theme(text = element_text(size = 14)) +
  labs(y = "", x = "Passage rate") +
  geom_point(aes(x = prop, y = year), shape = "x", 
            color = "red", size = 4) +
  geom_text(aes(x = 1, y = year, label = trials.x), nudge_x = .04,
            color = "darkgray") +
  annotate("text", x = .94, y = 2019, label = "n =", color = "darkgray")

ggsave("other/figures/successful_jags_run_hyperkappa_beta33_gamma.1_.01_allconverged_run030422.png", 
       width = 7, heigh = 5, dpi = 400)
```

# Video time series 
```{r}

# Match up year time series with 
fish_mod <- readRDS("other/output/fish_jags_mod_hyperkappa_beta3_3f_030322_all_converged.rds")
fish_mod

# collect all theta posterior draws and add fish/year info
theta_draws <- tidybayes::gather_draws(fish_mod, theta[i]) %>%
  left_join(data.frame(i = 1:15, 
                       year = c(2012:2017,2019,2012:2019))) %>%
  ungroup() %>%
  mutate(species = c(rep("American Shad", 21000), 
                     rep("River Herring spp.", 24000))) 

# collect omega (fish average) passage rate draws & add fish/year
# (just Shad in 2018 as that is the year with no passage info)
omega_draws_temp <- tidybayes::gather_draws(fish_mod, omega[i]) %>%
  filter(i == 1)

omega_draws_temp_shad <- mutate(omega_draws_temp, 
                      year = shad_hist$year[1]) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[2])) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[3])) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[4])) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[5])) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[6])) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[7])) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[8])) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[9])) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[10])) %>%
  bind_rows(mutate(omega_draws_temp, year = 2018)) %>%
  mutate(species = "American Shad")

omega_draws_temp_herring <- mutate(omega_draws_temp, 
                      year = shad_hist$year[1]) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[2])) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[3])) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[4])) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[5])) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[6])) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[7])) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[8])) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[9])) %>%
  bind_rows(mutate(omega_draws_temp, year = shad_hist$year[10])) %>%
  bind_rows(mutate(omega_draws_temp, year = 2018)) %>%
  mutate(species = "River Herring spp.")

omega_draws <- omega_draws_temp_shad %>%
  bind_rows(omega_draws_temp_herring)

rm(omega_draws_temp, 
   omega_draws_temp_shad, 
   omega_draws_temp_herring)

# join posterior draws to fish counts
fish_n_draws <- theta_draws %>%
  # add in global average (omega) passage draws for shad
  # in 2018 with no passage data  
  bind_rows(omega_draws) %>%
  # join with video count data
  left_join(v) %>%
  filter(is.na(n) != TRUE) %>% # remove years with no counts
  arrange(species, year)

# create corrected n and summarize draws
fish_n <- fish_n_draws %>%
  mutate(nhat = n / .value) %>%
  group_by(species, year) %>%
  summarise(nhat_mean = mean(nhat),
            nhat_q2.5 = quantile(nhat, .025),
            nhat_q97.5 = quantile(nhat, .975),
            nhat_q10 = quantile(nhat, .1),
            nhat_q90 = quantile(nhat, .9),
            n = mean(n),
            .groups = "keep") %>%
  bind_rows(data.frame(species = c("American Shad",
                                    "River Herring spp."),
                        year = rep(c(2000, 2004, 2006:2012),2),
                        nhat_mean = NA,
                        nhat_q2.5 = NA,
                        nhat_q97.5 = NA,
                        nhat_q10 = NA,
                        nhat_q90 = NA,
                        n = NA)) %>%
  arrange(species, year)

# plot nhat by species and year with credible intervals
fish_n %>%
  ggplot() +
  # geom_ribbon(aes(x = year, ymin = nhat_q2.5, 
  #                 ymax = nhat_q97.5),
  #             alpha = 0.5, fill = "steelblue") +
  geom_line(aes(x = year, y = nhat_mean+1),
            color = "dodgerblue", size = .5) +
  # geom_line(aes(x = year, y = n+1), size = 0.5, lty = 2, 
  #           color = "darkgray") +
  geom_point(aes(x = year, y = nhat_mean+1),
             color = "dodgerblue", size = 2) +
  geom_errorbar(aes(x = year, ymin = nhat_q2.5, 
                  ymax = nhat_q97.5),
              alpha = 1, color = "dodgerblue",
              width = 0.5) +
  facet_wrap(~species) +
  scale_y_log10() +
  theme_bw() +  
  theme(text = element_text(size = 14)) +
  theme(strip.background = element_rect(fill="white")) +
  labs(x = "", y = "Estimated run size (n)")
ggsave("other/figures/run_size_passage_corrected_points_run030322.png",
       height = 4, width = 7,
       dpi = 400)

# same using line and ribbon
# plot nhat by species and year with credible intervals
fish_n %>%
  ggplot() +
  geom_ribbon(aes(x = year, ymin = nhat_q2.5,
                  ymax = nhat_q97.5),
              alpha = 0.5, fill = "steelblue") +
  geom_line(aes(x = year, y = nhat_mean+1),
            color = "dodgerblue", size = 1) +
  # geom_line(aes(x = year, y = n+1), size = 0.5, lty = 2,
  #           color = "darkgray") +
  geom_point(aes(x = year, y = nhat_mean+1),
             color = "dodgerblue", size = 2, 
              data = filter(fish_n, year == 2005)) +
  geom_errorbar(aes(x = year, ymin = nhat_q2.5,
                  ymax = nhat_q97.5),
              alpha = 1, color = "dodgerblue",
              width = 0.5, 
              data = filter(fish_n, year == 2005)) +
  facet_wrap(~species) +
  scale_y_log10() +
  theme_bw() +  
  theme(text = element_text(size = 14)) +
  theme(strip.background = element_rect(fill="white")) +
  labs(x = "", y = "Estimated run size (n)")
ggsave("other/figures/run_size_passage_corrected_lines_run030322.png",
       height = 4, width = 7,
       dpi = 400)

```
# Attraction, staging, passage times
Warning: data are wrong at the moment until antennas are sorted out.
```{r}
fish_sum_plot = fish_sum %>%
  mutate(sp_cat = case_when(Common.Name %in% 
                              c("Blueback Herring", 
                                "River Herring") ~
                              "River Herring spp.",
                            Common.Name == "American Shad" ~
                              "American Shad",
                            TRUE ~ "NA")) %>%
  filter(sp_cat != "NA") %>%
  select(sp_cat, ends_with("days")) %>%
  pivot_longer(cols = ends_with("days")) %>%
  mutate(order = case_when(name == "attraction.days" ~ 1,
                           name == "staging.days" ~ 2,
                           name == "passage.days" ~ 3),
         name = forcats::fct_reorder(name, order))

fish_sum_plot %>%
  filter(value>=1,
         value < 300) %>%
ggplot() +
  geom_boxplot(aes(x = sp_cat, y = value, fill = sp_cat)) +
  facet_wrap(~name) +
  theme_bw() + 
  labs(x = "", y = "Days", fill = "") +
  theme(text = element_text(size = 14),
        axis.text.x = element_blank(),
        legend.position = "bottom") +
  scale_fill_manual(values = c("steelblue", "darkgreen"))

# ggsave("other/figures/transit_time_wrong.png",
#        height = 4, width = 7,
#        dpi = 400)
```


